apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: ecommerce
spec:
  encryptedData:
    JWT_SECRET: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal — replace with actual sealed value
  template:
    metadata:
      name: jwt-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: auth-db-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: product-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: product-db-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: order-db-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: payment-db-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: user-db-secret
      namespace: ecommerce
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: batch-db-secret
  namespace: ecommerce
spec:
  encryptedData:
    DB_USERNAME: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO... # sealed by kubeseal
  template:
    metadata:
      name: batch-db-secret
      namespace: ecommerce
    type: Opaque
